### ISSUE TITLE
Add a way to ignore PostBuild Event

### ISSUE THREAD

**Issue by DavidMarquezF** [MicrosoftTranslator/DocumentTranslationService#3]
Right now the postbuild event does a process to sign the dll. This is based in windows which means that we cannot build it in linux systems. 

It would be nice to add a property in order to not trigger this event.

**Comment by chriswendt1** [comment]
We could have another Build "Configuration" that uses the "Release" configuration but without the signing steps. Would that work?

**Comment by DavidMarquezF** [comment]
I have never tried this but from what you're saying it looks good. I think there should just be a specific build configuration without the signing.

**Comment by chriswendt1** [comment]
You don't have to recompile. It is provided as .Net bytecode in the "releases" folder. Look for a release that contains a .zip file. I don't always publish the zip file for every update, but if you need it, I'll do that from now on.

**Comment by DavidMarquezF** [comment]
Yes that would be nice, thank you!

**Comment by chriswendt1** [comment]
OK. Published zip for the 0.9.3.0 release and will do so going forward.

**Comment by chriswendt1** [comment]
Let me know if you find something missing or unclear with the zip.
